# Configuración de la función edge
[edge_functions]
  function = "http"
  path = "/test"

# Configuración básica de Netlify Forms
[build]
  publish = "dist" # Cambia "dist" por el directorio donde Netlify debe buscar tus archivos
  command = "npm run build" # El comando que usas para construir el proyecto

# Opcional: Redirección después del envío del formulario
[[redirects]]
  from = "/gracias"
  to = "/gracias.html"
  status = 200

# Configuración de los formularios
[build.environment]
  NETLIFY_FORMS = "true"

# Esta es una directiva que permite que los formularios sean procesados por Netlify
[[plugins]]
  package = "@netlify/plugin-functions"

# Configuración de funciones
[functions]
  node_bundler = "esbuild" # Define el empaquetador que usas para tus funciones
