
# Configuraci칩n b치sica de Netlify Forms
[build]
  publish = "dist" # Cambia "dist" por el directorio donde Netlify debe buscar tus archivos
  command = "npm run build" # El comando que usas para construir el proyecto

# Configuraci칩n de los formularios
[build.environment]
  NETLIFY_FORMS = "true"

# Esta es una directiva que permite que los formularios sean procesados por Netlify
[[plugins]]
  package = "@netlify/plugin-functions"

# Configuraci칩n de funciones
[functions]
  node_bundler = "esbuild" # Define el empaquetador que usas para tus funciones
