# Configuraci칩n b치sica de Netlify Forms
[build]
  publish = "dist"
  command = "npm run build"

# Configuraci칩n de los formularios
[build.environment]
  NETLIFY_FORMS = "true"

# Configuraci칩n de funciones
[functions]
  node_bundler = "esbuild"
