[build]
  publish = "dist"  # Cambia "dist" si tu carpeta de salida es diferente
  command = "npm run build"

[build.environment]
  NETLIFY_FORMS = "true"

[[plugins]]
  package = "@netlify/functions"  # Asegúrate de que el nombre sea correcto

[functions]
  node_bundler = "esbuild"  # O el empaquetador que estés usando
